# Generated by Django 4.1.2 on 2023-06-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rol_usuario_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
