# Generated by Django 4.1.2 on 2023-06-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
